/*This program demonstrates unchecked exceptions
Author : Team - J 
Version: 1.0*/

class except2  { 
	public void Error(){
		int i=22,j=0;
		try{
		i= i/j; //divide by zero exception
		}
		// try to comment try and catch.
		catch(ArithmeticException e){
		}
	}
	
	public static void main(String args[]){
		
		except2 e = new except2();
		// we are not handling the error here
		System.out.println(" before method call");
		e.Error();
		System.out.println(" after method call  " );
	}
}
 